package com.devlogai.generator;

import com.devlogai.model.Commit;

import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * Generates a beautiful Markdown devlog file from commits + AI summary.
 * Output goes to: devlogs/YYYY-MM-DD.md  (or  devlogs/week-YYYY-MM-DD.md)
 */
public class MarkdownGenerator {

    private static final String DEVLOGS_DIR = "devlogs";
    private static final DateTimeFormatter DISPLAY_FORMAT =
            DateTimeFormatter.ofPattern("MMMM dd, yyyy");

    public String generate(List<Commit> commits, String summary,
                           LocalDate from, LocalDate to, String mode) throws Exception {

        File dir = new File(DEVLOGS_DIR);
        if (!dir.exists()) dir.mkdirs();

        String filename = mode.equals("weekly")
                ? "week-" + from.toString() + ".md"
                : from.toString() + ".md";

        File outFile = new File(dir, filename);

        try (PrintWriter pw = new PrintWriter(new FileWriter(outFile))) {
            writeHeader(pw, from, to, mode);
            writeSummary(pw, summary);
            writeCommitTable(pw, commits);
            writeStats(pw, commits);
            writeFooter(pw, from);
        }

        return outFile.getPath();
    }

    private void writeHeader(PrintWriter pw, LocalDate from, LocalDate to, String mode) {
        String title = mode.equals("weekly")
                ? "📅 Weekly DevLog — " + from.format(DISPLAY_FORMAT) + " → " + to.format(DISPLAY_FORMAT)
                : "📅 DevLog — " + from.format(DISPLAY_FORMAT);

        pw.println("# " + title);
        pw.println();
        pw.println("> Generated by **[DevLog AI](https://github.com/goswamiSiddharth/devlog-ai)** " +
                   "🔥 ForkAndFire | Powered by Ollama (local LLM)");
        pw.println();
        pw.println("---");
        pw.println();
    }

    private void writeSummary(PrintWriter pw, String summary) {
        pw.println("## 🤖 AI Summary");
        pw.println();
        pw.println(summary);
        pw.println();
        pw.println("---");
        pw.println();
    }

    private void writeCommitTable(PrintWriter pw, List<Commit> commits) {
        pw.println("## 📝 Commits");
        pw.println();
        pw.println("| Hash | Message | Author | Date | +Lines | -Lines |");
        pw.println("|------|---------|--------|------|--------|--------|");

        for (Commit c : commits) {
            pw.printf("| `%s` | %s | %s | %s | +%d | -%d |%n",
                    c.getShortHash(),
                    escapeMarkdown(c.getMessage()),
                    c.getAuthor(),
                    c.getDate().toString(),
                    c.getInsertions(),
                    c.getDeletions());
        }

        pw.println();
        pw.println("---");
        pw.println();
    }

    private void writeStats(PrintWriter pw, List<Commit> commits) {
        int totalFiles    = commits.stream().mapToInt(Commit::getFilesChanged).sum();
        int totalAdded    = commits.stream().mapToInt(Commit::getInsertions).sum();
        int totalDeleted  = commits.stream().mapToInt(Commit::getDeletions).sum();

        pw.println("## 📊 Stats");
        pw.println();
        pw.println("| Metric | Value |");
        pw.println("|--------|-------|");
        pw.println("| Total Commits | " + commits.size() + " |");
        pw.println("| Files Changed | " + totalFiles + " |");
        pw.println("| Lines Added   | +" + totalAdded + " |");
        pw.println("| Lines Deleted | -" + totalDeleted + " |");
        pw.println();
        pw.println("---");
        pw.println();
    }

    private void writeFooter(PrintWriter pw, LocalDate date) {
        pw.println("*Generated on " + date.format(DISPLAY_FORMAT) +
                   " by [DevLog AI](https://github.com/goswamiSiddharth/devlog-ai) — " +
                   "Open Source Standup for Solo Developers 🔥*");
    }

    private String escapeMarkdown(String text) {
        return text.replace("|", "\\|").replace("\n", " ");
    }
}
