package com.devlogai.cli;

import java.io.*;
import java.nio.file.*;

/**
 * DevLog AI — `devlog init` command
 * Auto-sets up DevLog AI in any existing git project.
 *
 * What it does:
 *  1. Detects if current folder is a git repo
 *  2. Creates devlogs/ folder
 *  3. Creates docs/ folder with .nojekyll
 *  4. Creates docs/index.html placeholder
 *  5. Adds devlog entries to .gitignore if needed
 *  6. Creates .devlog-config with repo settings
 *  7. Prints next steps
 */
public class InitCommand {

    public void run() throws Exception {
        System.out.println("🚀 Initializing DevLog AI in current project...\n");

        // Step 1 — Check git repo
        if (!isGitRepo()) {
            System.out.println("❌ Not a git repository!");
            System.out.println("💡 Run 'git init' first, then run 'devlog init' again.");
            return;
        }
        System.out.println("✅ Git repository detected");

        // Step 2 — Create devlogs/ folder
        createFolder("devlogs");
        createFile("devlogs/.gitkeep", "");
        System.out.println("✅ Created devlogs/ folder");

        // Step 3 — Create docs/ folder
        createFolder("docs");
        createFile("docs/.nojekyll", "");
        System.out.println("✅ Created docs/ folder");

        // Step 4 — Create placeholder index.html
        if (!new File("docs/index.html").exists()) {
            createFile("docs/index.html", getPlaceholderHtml());
            System.out.println("✅ Created docs/index.html placeholder");
        } else {
            System.out.println("ℹ️  docs/index.html already exists — skipping");
        }

        // Step 5 — Create .devlog-config
        String repoUrl  = getGitRemoteUrl();
        String branch   = getGitBranch();
        String[] ownerRepo = extractOwnerRepo(repoUrl);

        String config = """
            # DevLog AI Configuration
            # Auto-generated by: devlog init
            # Docs: https://github.com/goswamiSiddharth/devlog-ai

            # Your GitHub repo (owner/repo format) — used for --issues flag
            github.owner=%s
            github.repo=%s

            # Default branch
            git.branch=%s

            # Ollama model to use (options: llama3, mistral, phi3, gemma2)
            ollama.model=llama3

            # Output format: markdown, site, both
            output.format=both
            """.formatted(ownerRepo[0], ownerRepo[1], branch);

        createFile(".devlog-config", config);
        System.out.println("✅ Created .devlog-config");

        // Step 6 — Update .gitignore
        updateGitignore();
        System.out.println("✅ Updated .gitignore");

        // Step 7 — Create GitHub Actions workflow
        createFolder(".github/workflows");
        if (!new File(".github/workflows/devlog-deploy.yml").exists()) {
            createFile(".github/workflows/devlog-deploy.yml", getWorkflowYml());
            System.out.println("✅ Created GitHub Actions workflow");
        } else {
            System.out.println("ℹ️  GitHub Actions workflow already exists — skipping");
        }

        // Done!
        printNextSteps(ownerRepo[0], ownerRepo[1]);
    }

    // ─── Git helpers ─────────────────────────────────────────────────

    private boolean isGitRepo() {
        return new File(".git").exists();
    }

    private String getGitRemoteUrl() {
        try {
            ProcessBuilder pb = new ProcessBuilder("git", "remote", "get-url", "origin");
            pb.redirectErrorStream(true);
            Process p = pb.start();
            String url = new BufferedReader(
                new InputStreamReader(p.getInputStream())).readLine();
            p.waitFor();
            return url != null ? url.trim() : "";
        } catch (Exception e) { return ""; }
    }

    private String getGitBranch() {
        try {
            ProcessBuilder pb = new ProcessBuilder("git", "branch", "--show-current");
            pb.redirectErrorStream(true);
            Process p = pb.start();
            String branch = new BufferedReader(
                new InputStreamReader(p.getInputStream())).readLine();
            p.waitFor();
            return branch != null ? branch.trim() : "main";
        } catch (Exception e) { return "main"; }
    }

    private String[] extractOwnerRepo(String remoteUrl) {
        // Handles:
        //   https://github.com/owner/repo.git
        //   git@github.com:owner/repo.git
        try {
            String cleaned = remoteUrl
                .replace("https://github.com/", "")
                .replace("git@github.com:", "")
                .replace(".git", "")
                .trim();
            String[] parts = cleaned.split("/");
            if (parts.length >= 2) return new String[]{parts[0], parts[1]};
        } catch (Exception ignored) {}
        return new String[]{"your-username", "your-repo"};
    }

    // ─── File helpers ─────────────────────────────────────────────────

    private void createFolder(String path) {
        new File(path).mkdirs();
    }

    private void createFile(String path, String content) throws Exception {
        File f = new File(path);
        f.getParentFile().mkdirs();
        try (PrintWriter pw = new PrintWriter(new FileWriter(f))) {
            pw.print(content);
        }
    }

    private void updateGitignore() throws Exception {
        File gitignore = new File(".gitignore");
        String existing = gitignore.exists()
            ? Files.readString(gitignore.toPath()) : "";

        StringBuilder toAdd = new StringBuilder();
        if (!existing.contains("target/"))       toAdd.append("target/\n");
        if (!existing.contains("*.class"))        toAdd.append("*.class\n");
        if (!existing.contains(".devlog-config")) toAdd.append("# DevLog AI\n.devlog-config\n");

        if (!toAdd.isEmpty()) {
            try (FileWriter fw = new FileWriter(gitignore, true)) {
                fw.write("\n" + toAdd);
            }
        }
    }

    // ─── Templates ───────────────────────────────────────────────────

    private String getWorkflowYml() {
        return """
            name: Deploy DevLog Site to GitHub Pages

            on:
              push:
                branches: [ main ]
              workflow_dispatch:

            permissions:
              contents: read
              pages: write
              id-token: write

            concurrency:
              group: "pages"
              cancel-in-progress: false

            jobs:
              deploy:
                environment:
                  name: github-pages
                  url: ${{ steps.deployment.outputs.page_url }}
                runs-on: ubuntu-latest
                steps:
                  - name: Checkout
                    uses: actions/checkout@v4
                  - name: Setup Pages
                    uses: actions/configure-pages@v4
                  - name: Upload artifact
                    uses: actions/upload-pages-artifact@v3
                    with:
                      path: 'docs'
                  - name: Deploy to GitHub Pages
                    id: deployment
                    uses: actions/deploy-pages@v4
            """;
    }

    private String getPlaceholderHtml() {
        return """
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="UTF-8"/>
              <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
              <title>DevLog — Powered by DevLog AI</title>
              <style>
                body{font-family:'Segoe UI',sans-serif;background:#0d1117;color:#e6edf3;
                     display:flex;align-items:center;justify-content:center;min-height:100vh;margin:0}
                .box{text-align:center;padding:40px}
                h1{font-size:2.5rem;margin-bottom:12px}
                p{color:#8b949e;margin-bottom:8px}
                code{background:#21262d;padding:2px 8px;border-radius:4px;color:#f0883e}
                a{color:#58a6ff;text-decoration:none}
              </style>
            </head>
            <body>
              <div class="box">
                <h1>🔥 DevLog AI</h1>
                <p>This project uses DevLog AI for standup tracking.</p>
                <p>Run <code>java -jar devlog-ai.jar generate</code> to create your first devlog!</p>
                <br/>
                <p><a href="https://github.com/goswamiSiddharth/devlog-ai">⭐ DevLog AI on GitHub</a></p>
              </div>
            </body>
            </html>
            """;
    }

    private void printNextSteps(String owner, String repo) {
        System.out.println("""

            ╔══════════════════════════════════════════════════╗
            ║   ✅ DevLog AI initialized successfully!         ║
            ╚══════════════════════════════════════════════════╝

            📋 Next steps:

            1️⃣  Generate your first devlog:
                java -jar devlog-ai.jar generate

            2️⃣  Include GitHub Issues:
                java -jar devlog-ai.jar generate --issues %s/%s

            3️⃣  Push and go live:
                git add .
                git commit -m "chore: initialize DevLog AI"
                git push

            4️⃣  Enable GitHub Pages:
                Settings → Pages → Source: GitHub Actions

            🔥 Happy logging! — ForkAndFire
            """.formatted(owner, repo));
    }
}
